DROP DATABASE IF EXISTS shopDB;

CREATE DATABASE IF NOT EXISTS shopDB;
USE shopDB;

CREATE TABLE categorie (
  idCat INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  nomCat VARCHAR(60) NOT NULL,
  PRIMARY KEY (idCat)
) ENGINE=INNODB AUTO_INCREMENT=1500 DEFAULT CHARSET=utf8;

CREATE TABLE gestionnaire (
  idGest INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  nomGest VARCHAR(45) NOT NULL,
  typeGest TINYINT(1) NOT NULL,
  login VARCHAR(20) NOT NULL,
  pwd VARCHAR(20) NOT NULL,
  actif TINYINT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (idGest)
) ENGINE=INNODB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8;

CREATE TABLE produit (
  codePro INT(8) UNSIGNED NOT NULL,
  nomPro VARCHAR(100) NOT NULL DEFAULT 'ND',
  prix DECIMAL(10,2) NOT NULL,
  qte INT(8) UNSIGNED NOT NULL,
  description VARCHAR(100) NOT NULL DEFAULT 'RAS',
  codeFour VARCHAR(12) NOT NULL,
  actif TINYINT(1) NOT NULL DEFAULT TRUE,
  idCategorie INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (codePro),
  KEY fk_idCategorie (idCategorie),
  CONSTRAINT codePro_domain CHECK(codePro BETWEEN 100000 AND 999999),
  CONSTRAINT fk_idCategorie FOREIGN KEY (idCategorie) REFERENCES categorie (idCat) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE photo (
  idPhoto INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  lienPhoto VARCHAR(150) NOT NULL,
  codePro INT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (idPhoto),
  KEY fk_photo_produit_idx (codePro),
  CONSTRAINT fk_photo_produit FOREIGN KEY (codePro) REFERENCES produit (codePro) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=250000 DEFAULT CHARSET=utf8;



CREATE TABLE gestionstock (
  idStock INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  qte INT(10) UNSIGNED NOT NULL,
  dateStock DATETIME NOT NULL,
  operation TINYINT(1) NOT NULL DEFAULT FALSE,
  idGest INT(10) UNSIGNED NOT NULL,
  codePro INT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (idStock),
  KEY fk_idGest_stock_idx (idGest),
  KEY fk_codePro_stock_idx (codePro),
  CONSTRAINT fk_codePro_stock FOREIGN KEY (codePro) REFERENCES produit (codePro),
  CONSTRAINT fk_idGest_stock FOREIGN KEY (idGest) REFERENCES gestionnaire (idGest) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=200000 DEFAULT CHARSET=utf8;


CREATE TABLE facture (
  idFac INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  dateFac DATETIME NOT NULL,
  remise DECIMAL(4,2) NOT NULL,
  montant DECIMAL(10,2) NOT NULL,
  tel VARCHAR(15),
  typeFac TINYINT(1) NOT NULL DEFAULT FALSE,
  idCaissiere INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (idFac),
  KEY fk_idCaiss_idx (idCaissiere),
  CONSTRAINT fk_idCaiss FOREIGN KEY (idCaissiere) REFERENCES gestionnaire (idGest) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=1005000 DEFAULT CHARSET=utf8;

CREATE TABLE lignefacture (
  idLFac INTEGER UNSIGNED UNIQUE AUTO_INCREMENT,
  codePro INT(10) UNSIGNED NOT NULL,
  idFac INT(10) UNSIGNED NOT NULL,
  prix DECIMAL(10,2) NOT NULL,
  qte SMALLINT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (codePro,idFac),
  KEY fk_idFac (idFac),
  CONSTRAINT fk_codePro FOREIGN KEY (codePro) REFERENCES produit (codePro),
  CONSTRAINT fk_idFac FOREIGN KEY (idFac) REFERENCES facture (idFac) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=450000 DEFAULT CHARSET=utf8;